version: '3.1'
services:
  db:
    image: mysql:8.2
    restart: always
    env_file: ".env"
    ports:
      - "3306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - altavo_network
  app:
    env_file: ".env"
    ports:
      - "8080:8080" 
    build: .
    depends_on:
      - db
    networks:
      - altavo_network

networks:
  altavo_network:
      
volumes:
  mysql-data:
